import { Analytics } from '#/components/analytics'
import { TailwindIndicator } from '#/components/tailwind-indicator'
import { ThemeProvider } from '#/components/theme-provider'
import { Toaster } from '#/components/toaster'
import { cn } from '#/lib/utils'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head/>
      <body
        className={cn(
          'min-h-screen text-primaryFg bg-primary font-sans antialiased transition-colors duration-700',inter.className
          
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <div className="flex min-h-screen flex-col">
         
{children}
</div>
<Analytics/>
        </ThemeProvider>
        <Toaster/>
        <TailwindIndicator/>

      </body>
    </html>
  )
}
