import '#/styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Analytics } from '#/components/analytics';
import { SiteFooter } from '#/components/footer';
import Header from '#/components/header';
import { TailwindIndicator } from '#/components/tailwind-indicator';
import { ThemeProvider } from '#/components/theme-provider';
import { Toaster } from '#/components/toaster';
import { cn } from '#/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          'min-h-screen text-primaryFg bg-primary font-sans antialiased transition-colors duration-700',
          inter.className,
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="container flex min-h-screen flex-col overflow-hidden bg-primary">
            <Header />
            <main className="min-h-[calc(100vh-80px)] flex-1 bg-item_brown ">
              {children}
            </main>
            <SiteFooter />
          </div>
          <Analytics />
        </ThemeProvider>
        <Toaster />
        <TailwindIndicator />
      </body>
    </html>
  );
}
